version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - cd profebot
      - mvn install
  post_build:
    commands:
      - echo post build started on `date`
      - mv build/libs/*.jar app.jar
artifacts:
  files:
    - app.jar
